#!/usr/bin/env python3
"""Interactive OAuth Setup Guide for YouTube and X.

This script provides step-by-step instructions with exact URLs
for setting up OAuth 2.0 authentication.

Usage:
    python scripts/setup_guide.py youtube
    python scripts/setup_guide.py x
    python scripts/setup_guide.py all
"""
import os
import sys

def print_youtube_guide():
    """Print YouTube OAuth setup guide."""
    print("=" * 70)
    print("YouTube OAuth 2.0 Setup Guide")
    print("=" * 70)
    print()
    print("Your email: j68251389@gmail.com")
    print()
    print("Step 1: Create Google Cloud Project")
    print("-" * 40)
    print("1. Open: https://console.cloud.google.com")
    print("2. Sign in with j68251389@gmail.com")
    print("3. Click 'Select a project' → 'New Project'")
    print("4. Name: ai-project-tracker")
    print("5. Click 'Create'")
    print()
    
    print("Step 2: Enable YouTube Data API v3")
    print("-" * 40)
    print("1. Go to: https://console.cloud.google.com/apis/library")
    print("2. Search: YouTube Data API v3")
    print("3. Click 'Enable'")
    print()
    
    print("Step 3: Configure OAuth Consent Screen")
    print("-" * 40)
    print("1. Go to: https://console.cloud.google.com/apis/credentials/consent")
    print("2. User Type: External")
    print("3. App name: AI Project Tracker")
    print("4. User support email: j68251389@gmail.com")
    print("5. Developer contact: j68251389@gmail.com")
    print("6. Click 'Save and Continue'")
    print("7. Scopes: Click 'Add or Remove Scopes' → Add 'youtube.readonly'")
    print("8. Click 'Save and Continue'")
    print("9. Test users: Add j68251389@gmail.com")
    print("10. Click 'Save and Continue'")
    print()
    
    print("Step 4: Create OAuth Credentials")
    print("-" * 40)
    print("1. Go to: https://console.cloud.google.com/apis/credentials")
    print("2. Click 'Create Credentials' → 'OAuth client ID'")
    print("3. Application type: Web application")
    print("4. Name: AI Project Tracker")
    print("5. Authorized redirect URIs: Add 'http://localhost'")
    print("6. Click 'Create'")
    print("7. Copy the Client ID and Client Secret")
    print()
    
    print("Step 5: Get Refresh Token")
    print("-" * 40)
    print("1. Open this URL in your browser (replace CLIENT_ID):")
    print()
    print("   https://accounts.google.com/o/oauth2/v2/auth?")
    print("   client_id=YOUR_CLIENT_ID&")
    print("   redirect_uri=http://localhost&")
    print("   response_type=code&")
    print("   scope=https://www.googleapis.com/auth/youtube.readonly&")
    print("   access_type=offline&")
    print("   prompt=consent")
    print()
    print("2. Sign in with j68251389@gmail.com")
    print("3. Click 'Allow'")
    print("4. You'll be redirected to localhost (page may show error - that's OK)")
    print("5. Copy the 'code' parameter from the URL")
    print()
    
    print("Step 6: Exchange Code for Tokens")
    print("-" * 40)
    print("Run this command (replace YOUR_CODE with the code from step 5):")
    print()
    print("   python -c \"")
    print("   import urllib.request, urllib.parse, json")
    print("   data = urllib.parse.urlencode({")
    print("       'client_id': 'YOUR_CLIENT_ID',")
    print("       'client_secret': 'YOUR_CLIENT_SECRET',")
    print("       'code': 'YOUR_CODE',")
    print("       'grant_type': 'authorization_code',")
    print("       'redirect_uri': 'http://localhost',")
    print("   }).encode('utf-8')")
    print("   req = urllib.request.Request('https://oauth2.googleapis.com/token', data=data, method='POST')")
    print("   req.add_header('Content-Type', 'application/x-www-form-urlencoded')")
    print("   with urllib.request.urlopen(req, timeout=15) as resp:")
    print("       tokens = json.loads(resp.read().decode('utf-8'))")
    print("       print('Refresh Token:', tokens['refresh_token'])")
    print("   \"")
    print()
    
    print("Step 7: Add to GitHub Secrets")
    print("-" * 40)
    print("Go to: https://github.com/Jacky-0809/ai-project-tracker/settings/secrets/actions")
    print()
    print("Add these secrets:")
    print("   YOUTUBE_CLIENT_ID = YOUR_CLIENT_ID")
    print("   YOUTUBE_CLIENT_SECRET = YOUR_CLIENT_SECRET")
    print("   YOUTUBE_REFRESH_TOKEN = YOUR_REFRESH_TOKEN")
    print()


def print_x_guide():
    """Print X OAuth setup guide."""
    print("=" * 70)
    print("X (Twitter) OAuth 2.0 Setup Guide")
    print("=" * 70)
    print()
    print("Step 1: Create Developer Account")
    print("-" * 40)
    print("1. Open: https://developer.x.com")
    print("2. Sign in with your X account")
    print("3. Apply for developer access (Free tier is OK)")
    print("4. Create a new Project and App")
    print()
    
    print("Step 2: Configure User Authentication")
    print("-" * 40)
    print("1. Go to your App settings")
    print("2. Click 'User authentication settings' → 'Set up'")
    print("3. App permissions: Read and write")
    print("4. Type of App: Web App, Automated App or Bot")
    print("5. Callback URI: http://localhost")
    print("6. Website URL: https://github.com/Jacky-0809/ai-project-tracker")
    print("7. Click 'Save'")
    print()
    
    print("Step 3: Get Client ID and Secret")
    print("-" * 40)
    print("1. Go to 'Keys and tokens' tab")
    print("2. Under 'OAuth 2.0 Client ID and Client Secret'")
    print("3. Click 'Regenerate'")
    print("4. Copy the Client ID and Client Secret")
    print()
    
    print("Step 4: Get User Access Token")
    print("-" * 40)
    print("1. Open this URL in your browser (replace CLIENT_ID):")
    print()
    print("   https://twitter.com/i/oauth2/authorize?")
    print("   client_id=YOUR_CLIENT_ID&")
    print("   redirect_uri=http://localhost&")
    print("   response_type=code&")
    print("   scope=bookmark.read+tweet.read+users.read&")
    print("   state=xyz&")
    print("   code_challenge=challenge&")
    print("   code_challenge_method=plain")
    print()
    print("2. Sign in with your X account")
    print("3. Click 'Authorize app'")
    print("4. You'll be redirected to localhost (page may show error - that's OK)")
    print("5. Copy the 'code' parameter from the URL")
    print()
    
    print("Step 5: Exchange Code for Token")
    print("-" * 40)
    print("Run this command (replace YOUR_CODE with the code from step 4):")
    print()
    print("   python -c \"")
    print("   import urllib.request, urllib.parse, json")
    print("   data = urllib.parse.urlencode({")
    print("       'client_id': 'YOUR_CLIENT_ID',")
    print("       'client_secret': 'YOUR_CLIENT_SECRET',")
    print("       'code': 'YOUR_CODE',")
    print("       'grant_type': 'authorization_code',")
    print("       'redirect_uri': 'http://localhost',")
    print("       'code_verifier': 'challenge',")
    print("   }).encode('utf-8')")
    print("   req = urllib.request.Request('https://api.twitter.com/2/oauth2/token', data=data, method='POST')")
    print("   req.add_header('Content-Type', 'application/x-www-form-urlencoded')")
    print("   with urllib.request.urlopen(req, timeout=15) as resp:")
    print("       tokens = json.loads(resp.read().decode('utf-8'))")
    print("       print('Access Token:', tokens['access_token'])")
    print("   \"")
    print()
    
    print("Step 6: Get Your User ID")
    print("-" * 40)
    print("Run this command (replace YOUR_TOKEN with the access token):")
    print()
    print("   python -c \"")
    print("   import urllib.request, json")
    print("   req = urllib.request.Request(")
    print("       'https://api.twitter.com/2/users/me',")
    print("       headers={'Authorization': 'Bearer YOUR_TOKEN'}")
    print("   )")
    print("   with urllib.request.urlopen(req, timeout=30) as resp:")
    print("       data = json.loads(resp.read().decode('utf-8'))")
    print("       print('User ID:', data['data']['id'])")
    print("   \"")
    print()
    
    print("Step 7: Add to GitHub Secrets")
    print("-" * 40)
    print("Go to: https://github.com/Jacky-0809/ai-project-tracker/settings/secrets/actions")
    print()
    print("Add these secrets:")
    print("   X_USER_ID = YOUR_USER_ID")
    print("   X_ACCESS_TOKEN = YOUR_ACCESS_TOKEN")
    print()


def print_all_guide():
    """Print complete setup guide."""
    print_youtube_guide()
    print("\n" + "=" * 70 + "\n")
    print_x_guide()
    
    print("=" * 70)
    print("Final Steps")
    print("=" * 70)
    print()
    print("After adding all secrets to GitHub:")
    print()
    print("1. Test locally:")
    print("   python scripts/run.py --date 2026-09-04")
    print()
    print("2. Commit and push:")
    print("   git add .")
    print("   git commit -m 'feat: add OAuth tokens for bookmarks'")
    print("   git push")
    print()
    print("3. Wait for CI to complete:")
    print("   https://github.com/Jacky-0809/ai-project-tracker/actions")
    print()
    print("4. Check the report:")
    print("   https://jacky-0809.github.io/ai-project-tracker/output/Ai_skill_2026_09_04/index.html")
    print()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/setup_guide.py [youtube|x|all]")
        sys.exit(1)
    
    platform = sys.argv[1].lower()
    
    if platform == "youtube":
        print_youtube_guide()
    elif platform == "x":
        print_x_guide()
    elif platform == "all":
        print_all_guide()
    else:
        print(f"Unknown platform: {platform}")
        print("Usage: python scripts/setup_guide.py [youtube|x|all]")
        sys.exit(1)
